/**
 * User Action Types
 */

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';

export const USER_SIGNUP = 'USER_SIGNUP';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';

export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const USER_SIGNUP_ERROR = 'USER_SIGNUP_ERROR';

export const CLEAR_USER_TOKEN = 'CLEAR_USER_TOKEN';
export const CLEAR_USER_ERROR = 'CLEAR_USER_ERROR';

/**
 * Businesses Action Types
 */
export const FETCHING_BUSINESSES = 'FETCHING_BUSINESSES';
export const FETCHING_BUSINESSES_SUCCESS = 'FETCHING_BUSINESSES_SUCCESS';
export const FETCHING_BUSINESSES_ERROR = 'FETCHING_BUSINESSES_ERROR';

export const CLEAR_BUSINESSES_ERROR = 'CLEAR_BUSINESSES_ERROR';
export const CLEAR_QUERY_ERROR = 'CLEAR_QUERY_ERROR';

export const FETCHING_BUSINESS = 'FETCHING_BUSINESS';
export const FETCHING_BUSINESS_SUCCESS = 'FETCHING_BUSINESS_SUCCESS';
export const FETCHING_BUSINESS_ERROR = 'FETCHING_BUSINESS_ERROR';

export const FETCHING_BUSINESS_PROFILE = 'FETCHING_BUSINESS_PROFILE';
export const FETCHING_BUSINESS_PROFILE_SUCCESS =
  'FETCHING_BUSINESS_PROFILE_SUCCESS';
export const FETCHING_BUSINESS_PROFILE_ERROR =
  'FETCHING_BUSINESS_PROFILE_ERROR';

export const FETCHING_BUSINESS_REVIEWS = 'FETCHING_BUSINESS_REVIEWS';
export const FETCHING_BUSINESS_REVIEWS_SUCCESS =
  'FETCHING_BUSINESS_REVIEWS_SUCCESS';
export const FETCHING_BUSINESS_REVIEWS_ERROR =
  'FETCHING_BUSINESS_REVIEWS_ERROR';

export const ADDING_BUSINESS_REVIEW = 'ADDING_BUSINESS_REVIEW';
export const ADDING_BUSINESS_REVIEW_SUCCESS = 'ADDING_BUSINESS_REVIEW_SUCCESS';
export const ADDING_BUSINESS_REVIEW_ERROR = 'ADDING_BUSINESS_REVIEW_ERROR';

export const QUERY_BUSINESS = 'QUERY_BUSINESS';
export const QUERY_BUSINESS_SUCCESS = 'QUERY_BUSINESS_SUCCESS';
export const QUERY_BUSINESS_ERROR = 'QUERY_BUSINEES_ERROR';


export const ADDING_BUSINESS = 'ADDING_BUSINESS';
export const ADDING_BUSINESS_SUCCESS = 'ADDING_BUSINESS_SUCCESS';
export const ADDING_BUSINESS_ERROR = 'ADDING_BUSINESS_ERROR';

export const UPDATE_BUSINESS = 'UPDATE_BUSINESS';
export const UPDATE_BUSINESS_SUCCESS = 'UPDATE_BUSINESS_SUCCESS';
export const UPDATE_BUSINESS_ERROR = 'UPDATE_BUSINESS_ERROR';
